# Spring Data MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=2717
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.database=mydatabase
spring.data.mongodb.username=root
spring.data.mongodb.password=rootpassword
