# Server Configuration
spring.application.name=spring-roulette-backend
spring.application.version=1.0.0
spring.application.description=Backend for Spring Roulette Game
spring.application.author=Wilson Sam


spring.profiles.active=prod


server.port=9090

# Logging Configuration
#logging.level.root=INFO
#debug=true
#logging.level.org.springframework.data.mongodb.repository.config=DEBUG
#logging.level.org.springframework.data.repository.config=DEBUG
#logging.level.org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider=DEBUG
#
