import React from 'react';
import { View, Text, Image, StyleSheet } from '@react-pdf/renderer';

const Header = ({ title, logoSrc, clientLogo, role = '????', formattedDate }) => {

  const getHeadingName = (role) => {
    if (role === 'Admin') {
      return 'MONTHLY METERS REPORT';
    } else if (role === 'Manager') {
      return 'DAILY METERS REPORT';
    } else {
      return 'SHIFT REPORT';
    }
  };

  return (
    <View
      style={{
        width: '100%',
        height: '150px',
        border: '1px solid #ddd',
        marginBottom: '10px',
      }}
    >
      <View
        style={{
          flexDirection: 'row',
          height: '70px',
          justifyContent: 'space-between',
          alignItems: 'center',
          paddingVertical: '6px',
          paddingHorizontal: '12px',
          borderBottom: '1px solid #ddd',
        }}
      >
        <Image src={logoSrc} style={{ height: '40px' }} />
        <View style={{ alignItems: 'center' }}>
          <Text
            style={{
              fontSize: '25px',
              fontWeight: 'ultrabold',
              textAlign: 'center',
            }}
          >
            {getHeadingName(role)}
          </Text>
          <Text
            style={{
              fontSize: '15px',
              fontWeight: 'normal',
              textAlign: 'center',
            }}
          >
            Cadillac Diamond Casino
          </Text>
        </View>
        <Image src={clientLogo} style={{ height: '40px' }} />
      </View>
      <View
        style={{
          flexDirection: 'row',
          height: '80px',
          justifyContent: 'space-between',
        }}
      >
        <View
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            width: '30%',
            padding: '6px',
          }}
        >
          <Text
            style={{
              fontWeight: 'extrabold',
              textAlign: 'center',
              fontSize: '9px',
              paddingBottom: '5px',
            }}
          >
            WILDACE PRIVATE LIMITED
          </Text>
          <Text
            style={{
              textAlign: 'center',
              fontSize: '8px',
              paddingHorizontal: '8px',
            }}
          >
            Wildace Private Limited, SRIT House, ITPL Main Rd, Kundalahalli,
            Brookefield, Bengaluru, Karnataka 560037
          </Text>
        </View>
        <View
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            width: '40%',
            paddingHorizontal: '6px',
            paddingVertical: '2px',
            borderLeft: '1px solid #ddd',
            borderRight: '1px solid #ddd',
          }}
        >
          <View
            style={{
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'space-between',
              gap: '30px',
              width: '78%',
              padding: '1.3px',
            }}
          >
            <Text style={{ fontWeight: 'semibold', fontSize: '8px' }}>
              CATEGORY
            </Text>
            <Text style={{ fontSize: '8px' }}>{getHeadingName(role)}</Text>
          </View>
          <View
            style={{
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'space-between',
              gap: '30px',
              width: '78%',
              padding: '1.3px',
            }}
          >
            <Text style={{ fontWeight: 'semibold', fontSize: '8px' }}>
              CREATED AT
            </Text>
            <Text style={{ fontSize: '8px' }}>{formattedDate}</Text>
          </View>
          <View
            style={{
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'space-between',
              gap: '30px',
              width: '78%',
              padding: '1.3px',
            }}
          >
            <Text style={{ fontWeight: 'semibold', fontSize: '8px' }}>
              GENERATED BY
            </Text>
            <Text style={{ fontSize: '8px' }}>{role}</Text>
          </View>
        </View>
        <View
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            width: '30%',
            padding: '6px',
          }}
        >
          <Text
            style={{
              fontWeight: 'extrabold',
              textAlign: 'center',
              fontSize: '9px',
              paddingBottom: '5px',
            }}
          >
            CADILLAC DIAMOND CASINO
          </Text>
          <Text
            style={{
              textAlign: 'center',
              fontSize: '8px',
              paddingHorizontal: '8px',
            }}
          >
            Double Tree Hilton, Kadamba Plateau, Panjim, Old Goa, Road,
            Ribandar, Goa 403006
          </Text>
        </View>
      </View>
    </View>
  );
};

export default Header;
