/*
 * Copyright 2024 Wildace Private Limited - All Rights Reserved
 *
 * Licensed under Wildace Software License Agreement ("License").
 * You may not use this file except in compliance with the License.
 *
 * NOTICE
 * ALL INFORMATION CONTAINED HEREIN IS, AND REMAINS THE PROPERTY OF WILDACE PRIVATE LIMITED.
 * THE INTELLECTUAL AND TECHNICAL CONCEPTS CONTAINED HEREIN ARE PROPRIETARY TO WILDACE PRIVATE LIMITED AND ARE PROTECTED BY TRADE SECRET OR COPYRIGHT LAW.
 * DISSEMINATION OF THIS INFORMATION OR REPRODUCTION OF THIS MATERIAL IS STRICTLY FORBIDDEN UNLESS PRIOR WRITTEN PERMISSION IS OBTAINED FROM WILDACE PRIVATE LIMITED.
 * **********************************************************************************************************************************************************************
 * Change History
 * **********************************************************************************************************************************************************************
 * |     Date      |     Name     |      Change     |      Details
 * |  02/07/2025   | Wilson Sam   |     Created     |  File Creation
 * |  30/07/2025   | Wilson Sam   |     Updated     |  Added new fields for Game Result Response
 * **********************************************************************************************************************************************************************
 * */
package com.wildace.poker.jacksorbetter.dto;


import java.time.LocalDateTime;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Response object representing a game result (deal or draw) for Jacks or Better.
 */
@Schema(
    description = "Response containing the details and results of a Jacks or Better game session (deal or draw)."
)
public class GameResultResponse {

    @Schema(
        description = "Unique session identifier for the game.",
        example = "c1dd8ac1-1d8c-4f61-95b2-cccd0e8c9e64"
    )
    private String sessionId;

    @Schema(description = "User unique identifier (UID)", example = "53ce81df")

    private String userId;

    @Schema(description = "Electronic Gaming Machine (EGM) identifier", example = "WAS-2001")

    private String egmId;

    @Schema(
        description = "Action type. Either 'deal' or 'draw'.",
        example = "draw"
    )
    private String action; // "deal" or "draw"

    @Schema(
        description = "Game start timestamp (in yyyy-MM-dd HH:mm:ss format, IST).",
        example = "2025-07-08 15:55:12"
    )
    private String gameStart;

    @Schema(
        description = "Game end timestamp (in yyyy-MM-dd HH:mm:ss format, IST).",
        example = "2025-07-08 15:55:25"
    )
    private String gameEnd;

    @Schema(
        description = "List of hands, each hand being a list of 5 card representations.",
        implementation = CardDto.class
    )
    private List<List<CardDto>> hands;

    @Schema(
        description = "Total bet amount for the session.",
        example = "5.0"
    )
    private double betAmount;

    @Schema(
        description = "Total win amount credited in this session.",
        example = "10.0"
    )
    private double winAmount;

    @Schema(
        description = "Wallet balance before the game.",
        example = "100.0"
    )
    private double oldCredit;

    @Schema(
        description = "Wallet balance after the game.",
        example = "105.0"
    )
    private double newCredit;

    @Schema(
        description = "Number of coins bet per hand.",
        example = "1"
    )
    private int coin;

    @Schema(
        description = "Number of hands played.",
        example = "3"
    )
    private int numberOfHands;

    @Schema(
        description = "List of payouts for each hand.",
        example = "[0, 5, 10]"
    )
    private List<Integer> payouts;
    
    @Schema(
		description = "List of holds for the draw action, indicating which cards were held.",
		example = "[0,1]"
	)
    private List<Integer> holds;         // For draw

    @Schema(
		description = "List of results for each hand, e.g., 'Pair', 'Three of a Kind', etc.",
		example = "[\"Pair\", \"Three of a Kind\", \"Flush\"]"
	)
    private List<String> results;        // For results of the game
    

    // Getters & Setters (can be generated by IDE)
    public String getSessionId() { return sessionId; }
    public void setSessionId(String sessionId) { this.sessionId = sessionId; }
    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }
    public String getEgmId() { return egmId; }
    public void setEgmId(String egmId) { this.egmId = egmId; }
    public String getAction() { return action; }
    public void setAction(String action) { this.action = action; }
    public String getGameStart() { return gameStart; }
    public void setGameStart(String gameStart) { this.gameStart = gameStart; }
    public String getGameEnd() { return gameEnd; }
    public void setGameEnd(String gameEnd) { this.gameEnd = gameEnd; }
    public List<List<CardDto>> getHands() { return hands; }
    public void setHands(List<List<CardDto>> hands) { this.hands = hands; }
    public double getBetAmount() { return betAmount; }
    public void setBetAmount(double betAmount) { this.betAmount = betAmount; }
    public double getWinAmount() { return winAmount; }
    public void setWinAmount(double winAmount) { this.winAmount = winAmount; }
    public double getOldCredit() { return oldCredit; }
    public void setOldCredit(double oldCredit) { this.oldCredit = oldCredit; }
    public double getNewCredit() { return newCredit; }
    public void setNewCredit(double newCredit) { this.newCredit = newCredit; }
    public int getCoin() { return coin; }
    public void setCoin(int coin) { this.coin = coin; }
    public int getNumberOfHands() { return numberOfHands; }
    public void setNumberOfHands(int numberOfHands) { this.numberOfHands = numberOfHands; }
    public List<Integer> getPayouts() { return payouts; }
    public void setPayouts(List<Integer> payouts) { this.payouts = payouts; }
    public List<Integer> getHolds() { return holds; }
    public void setHolds(List<Integer> holds) { this.holds = holds; }
    public List<String> getResults() { return results; }
    public void setResults(List<String> results) { this.results = results; }

    // Optional: static converter for entity to DTO
    public static GameResultResponse fromAuditLog(GameAuditLog log) {
        GameResultResponse dto = new GameResultResponse();
        dto.setSessionId(log.getSessionId());
        dto.setUserId(log.getUserId());
        dto.setEgmId(log.getEgmId());
        dto.setAction(log.getAction());
        dto.setGameStart(log.getGameStart());
        dto.setGameEnd(log.getGameEnd());
        dto.setHands(log.getHands());
        dto.setBetAmount(log.getBetAmount());
        dto.setWinAmount(log.getWinAmount());
        dto.setOldCredit(log.getOldCredit());
        dto.setNewCredit(log.getNewCredit());
        dto.setCoin(log.getCoin());
        dto.setNumberOfHands(log.getNumberOfHands());
        dto.setPayouts(log.getPayouts());
        dto.setHolds(log.getHolds());
        dto.setResults(log.getResults());
        return dto;
    }
    public static GameResultResponse fromAuditLog(DeucesWildGameAuditLog log) {
    	GameResultResponse dto = new GameResultResponse();
    	dto.setSessionId(log.getSessionId());
    	dto.setUserId(log.getUserId());
    	dto.setEgmId(log.getEgmId());
    	dto.setAction(log.getAction());
    	dto.setGameStart(log.getGameStart());
    	dto.setGameEnd(log.getGameEnd());
    	dto.setHands(log.getHands());
    	dto.setBetAmount(log.getBetAmount());
    	dto.setWinAmount(log.getWinAmount());
    	dto.setOldCredit(log.getOldCredit());
    	dto.setNewCredit(log.getNewCredit());
    	dto.setCoin(log.getCoin());
    	dto.setNumberOfHands(log.getNumberOfHands());
    	dto.setPayouts(log.getPayouts());
    	dto.setHolds(log.getHolds());
    	dto.setResults(log.getResults());
    	return dto;
    }
    
}
