spring:
  data:
    mongodb:
      host: mongo1
      port: 27017
      database: mydatabase
      username: root
      password: rootpassword
  application:
    name: spring-roulette-backend		

springdoc:
  api-docs:
     path: /api-docs

logging:
  level:
    org.springframework.web: INFO
server:
  port: 9090
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 60000
